### ISSUE TITLE
Ci pipelines are failing for dot net repo

### ISSUE THREAD

**Issue by vigneshren** [kolosovpetro/DotnetTemplate#4]
hi team ,
our ci pipeline is suddenly failing with below error can someone please help! 
thanks in advance!

![image](https://github.com/kolosovpetro/DotnetTemplate/assets/158045313/c42f08bb-6fee-431f-9798-6b94ce2f8b2c)

**Comment by kolosovpetro** [comment]
> hi team , our ci pipeline is suddenly failing with below error can someone please help! thanks in advance!
> 
> ![image](https://private-user-images.githubusercontent.com/158045313/341475974-c42f08bb-6fee-431f-9798-6b94ce2f8b2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzIwNTcsIm5iZiI6MTcxOTEzMTc1NywicGF0aCI6Ii8xNTgwNDUzMTMvMzQxNDc1OTc0LWM0MmYwOGJiLTZmZWUtNDMxZi05Nzk4LTZiOTRjZTJmOGIyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QwODM1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjkwMDBkMWUzYTc5NzU0ZjMyZmY5MDI1NGJmYzRlMmFmZGM4NDk3MmU5NzAwOTJhOTZhYmI0NDkzOWNiODZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nj7pdjqMWf5cPv_yGeAhEUASPzuDY1IzMpIu6l1TF8Y)

Please share your build definition in YAML

**Comment by vigneshren** [comment]
hi @kolosovpetro  , i have fixed the issue ,thank you for the response
